name: CI

on: [push, pull_request]

jobs:
  # Build and test for V1
  build-and-test-v1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [csharp, python]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup for .NET (V1)
    - name: Set up .NET
      if: matrix.language == 'csharp'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Debug file structure
    - name: Debug File Structure
      run: ls -R ../..

    # Build .NET project (V1)
    - name: Build .NET project (V1)
      if: matrix.language == 'csharp'
      run: dotnet build --configuration Release ../../Werehouses/V1/Cargohub/Werehouses.csproj

    # Test .NET project (V1)
    - name: Test .NET project (V1)
      if: matrix.language == 'csharp'
      run: dotnet test --no-build --verbosity normal --configuration Release ../../Werehouses/V1/Cargohub/Werehouses.csproj

    # Setup for Python (shared with V2)
    - name: Set up Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Install Python dependencies (shared with V2)
    - name: Install dependencies
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run Python tests (shared with V2)
    - name: Run Python tests
      if: matrix.language == 'python'
      run: |
        if [ -f pytest.ini ]; then pytest; fi

  # Build and test for V2
  build-and-test-v2:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [csharp, python]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup for .NET (V2)
    - name: Set up .NET
      if: matrix.language == 'csharp'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Debug file structure
    - name: Debug File Structure
      run: ls -R ../..

    # Build .NET project (V2)
    - name: Build .NET project (V2)
      if: matrix.language == 'csharp'
      run: dotnet build --configuration Release ../../Werehouses/V2/Cargohub/Werehouses.csproj

    # Test .NET project (V2)
    - name: Test .NET project (V2)
      if: matrix.language == 'csharp'
      run: dotnet test --no-build --verbosity normal --configuration Release ../../Werehouses/V2/Cargohub/Werehouses.csproj

    # Setup for Python (shared with V1)
    - name: Set up Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Install Python dependencies (shared with V1)
    - name: Install dependencies
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run Python tests (shared with V1)
    - name: Run Python tests
      if: matrix.language == 'python'
      run: |
        if [ -f pytest.ini ]; then pytest; fi
