name: CI

on: [push, pull_request]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [csharp, python]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      if: matrix.language == 'csharp'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build .NET project
      if: matrix.language == 'csharp'
      run: dotnet build --configuration Release ../Cargohub/Werehouses.csproj

    - name: Test .NET project
      if: matrix.language == 'csharp'
      run: dotnet test --no-build --verbosity normal --configuration Release ../Cargohub/Werehouses.csproj

    - name: Set up Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      if: matrix.language == 'python'
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python tests
      if: matrix.language == 'python'
      run: |
        if [ -f pytest.ini ]; then pytest; fi